# Change these first
owner: gon-alt # Your GitHub organization or username, where this repository lives
repo: estado_de_sitiosWeb # The name of this repository

sites:
  - name: Geco
    url: https://gon-alt.github.io/geco/
  - name: el_cabure
    url: https://gon-alt.github.io/el_cabure/
  - name: decoMuebles
    url: https://gon-alt.github.io/decoMuebles/
  - name: Foster Viajes
    url: https://fosterviajes.tur.ar/
    
assignees:
  - gon-alt

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  #apiBaseUrl: https://api.github.com
  theme: dark
  baseUrl: /estado_de_sitiosWeb
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime de Sitios Web
  introTitle: "**Upptime** Bienvenido, esta es una pagina para corroborar el estado de tus sitios web, esperemos que todo vaya bien! :) by GitHub."
  introMessage: A continuación encontrarás un resumen del estado de sus sitios que se actualiza con una frecuencia de 10 minutos aproximadamente, así que si tu sitio muestra un estado diferente al que aparece en esta página ten paciencia y espera la actualización del estado. 
  navbar:
    - title: Status
      href: https://gon-alt.github.io/estado_de_sitiosWeb/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
